# Generated by Django 3.0.7 on 2020-06-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200620_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
