# Generated by Django 3.0.7 on 2020-06-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200621_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
