# Generated by Django 3.0.7 on 2020-07-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20200715_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_price',
            field=models.FloatField(default=0, max_length=4),
        ),
    ]
