# Generated by Django 3.0.7 on 2020-07-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_order_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
    ]
