# Generated by Django 3.0.7 on 2020-07-29 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_aboutview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutView',
        ),
    ]
