# Generated by Django 3.0.7 on 2020-08-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_course_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='myapp/media/profile_pics'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
